apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gitea
  name: gitea-http
  namespace: gitea
spec:
  host: gitea.example.com
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
  to:
    kind: Service
    name: gitea-http
    weight: 100
  wildcardPolicy: None
